-- prototypes/beam.lua ------------------------------------------------------------
-- The lance: what the installation actually fires.
--
-- A core and a halo at every C.beam_steps() fraction (1%, then every 5% to
-- 100% -- 42 prototypes), all generated by lib/beam.lua. ARCHITECTURE.md rule
-- 3: the second thing that looks like the first is a builder call, not a copy.
--
-- WHY ONE PER STEP
-- A prototype's scale is settled in the data stage and has no runtime handle --
-- there is no LuaEntity.beam_scale. The lance's width is how the player reads
-- the energy in it, so it is built fine enough that every 5% of charge shows.
--
-- WHAT THIS FILE DOES NOT DO
-- No `action`. The beams carry no damage of their own -- scripts/beam.lua does
-- the scouring and scripts/impact.lua does the detonation. That is deliberate,
-- not an omission: a beam's action fires against what the beam is TARGETING, and
-- these are created with a target_position rather than a target entity. Whether
-- the engine still runs an action in that case is not settled by the 2.0.77
-- spec, and a weapon whose damage rests on an unsettled reading is a weapon that
-- silently does nothing. Explained again at the head of lib/beam.lua.
----------------------------------------------------------------------------------

local C     = require("config")
local N     = require("lib.names")
local blib  = require("lib.beam")
local heat  = require("lib.heat")

local B = C.beam

--- One layer's prototype at one yield.
-- @param layer "core"|"halo"
-- @param spec  C.beam.core or C.beam.halo
-- @param fraction number  the yield step
local function lance_at(layer, spec, fraction, hstep, kelvin, kind)
  -- The size the yield buys. Everything visual is multiplied by this one number,
  -- so a small shot is a proportionally small beam and nothing can drift.
  local size = C.beam_size(fraction)
  -- The colour is the temperature's -- see C.heat. spec.tint is not used.
  local tint, light_tint = heat.lance_tints(layer, kelvin)

  return blib.lance{
    name       = N.lance(layer, fraction, hstep, kind),
    kind       = kind,
    head_disc  = not B.spans.enabled,
    localised_name = {"entity-name.oppenheimer-lance", layer, N.yield_tag(fraction)},
    scale      = C.beam_scale(spec.scale_mult) * size,
    width      = 0.5 * spec.width_mult * size,
    tint       = tint,
    light_tint = light_tint,
    blend      = spec.blend,
    -- nil for the halo, which is the point -- see C.beam.core.ground_mult.
    ground_scale = spec.ground_mult
                   and (C.beam_scale(spec.ground_mult) * size)
                   or nil,
  }
end

local lances = {}

-- "end" is the whole beam or the tip span; "mid" is the interior of a chained lance.
local KINDS = B.spans.enabled and {"end", "mid"} or {"end"}

-- Every C.beam.width_step, not every detonation step -- see C.beam.width_step.
for _, f in ipairs(C.beam_steps()) do
  for h, k in ipairs(heat.steps()) do
    for _, kind in ipairs(KINDS) do
      lances[#lances + 1] = lance_at("halo", B.halo, f, h, k, kind)
      lances[#lances + 1] = lance_at("core", B.core, f, h, k, kind)
    end
  end
end

data:extend(lances)
