-- lib/foundation_plan.lua ----------------------------------------------------
-- STATIC floor plan of the 41 x 41 pad, generated by tools/bp_to_plan.py
-- <blueprint.txt> then tools/clip_plan.py. Do not hand-edit the rows below.
--------------------------------------------------------------------------------
local REF   = "refined-concrete"
local CONC  = "concrete"
local STONE = "stone-path"
local HAZ_L = "refined-hazard-concrete-left"
local HAZ_R = "refined-hazard-concrete-right"

-- Row run-length encoded: {dy, {{dx_start, dx_end, tile}, ...}}
local rows = {
  {-20, {{-20,-11,HAZ_L}, {-10,-5,HAZ_R}, {-4,-3,STONE}, {-2,2,HAZ_R}, {3,4,STONE}, {5,20,HAZ_R}}},
  {-19, {{-20,-11,HAZ_L}, {-10,-5,HAZ_R}, {-4,-3,STONE}, {-2,2,HAZ_R}, {3,4,STONE}, {5,20,HAZ_R}}},
  {-18, {{-20,-11,HAZ_L}, {-10,-5,HAZ_R}, {-4,-3,STONE}, {-2,2,HAZ_R}, {3,4,STONE}, {5,20,HAZ_R}}},
  {-17, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-16, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-15, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-14, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-13, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-12, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-11, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,17,HAZ_L}, {18,20,HAZ_R}}},
  {-10, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,9,HAZ_R}, {10,17,HAZ_L}, {18,20,HAZ_R}}},
  {-9, {{-20,-20,HAZ_L}, {-19,-18,HAZ_R}, {-17,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,7,REF}, {8,20,HAZ_R}}},
  {-8, {{-20,-9,HAZ_R}, {-8,-3,STONE}, {-2,2,REF}, {3,8,STONE}, {9,20,HAZ_R}}},
  {-7, {{-20,-9,HAZ_R}, {-8,-3,STONE}, {-2,2,HAZ_R}, {3,8,STONE}, {9,20,HAZ_R}}},
  {-6, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {-5, {{-20,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,20,STONE}}},
  {-4, {{-20,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,20,STONE}}},
  {-3, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {-2, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {-1, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {0, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {1, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {2, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {3, {{-20,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,20,STONE}}},
  {4, {{-20,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,20,STONE}}},
  {5, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,-6,HAZ_R}, {-5,5,CONC}, {6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {6, {{-20,-18,HAZ_R}, {-17,-9,REF}, {-8,-7,STONE}, {-6,6,HAZ_R}, {7,8,STONE}, {9,17,REF}, {18,20,HAZ_R}}},
  {7, {{-20,-9,HAZ_R}, {-8,8,STONE}, {9,16,HAZ_L}, {17,20,HAZ_R}}},
  {8, {{-20,-19,HAZ_L}, {-18,-9,HAZ_R}, {-8,8,STONE}, {9,17,HAZ_L}, {18,20,HAZ_R}}},
  {9, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {10, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {11, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {12, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {13, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {14, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {15, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {16, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {17, {{-20,-8,HAZ_L}, {-7,-5,REF}, {-4,-3,STONE}, {-2,2,REF}, {3,4,STONE}, {5,6,REF}, {7,17,HAZ_L}, {18,20,HAZ_R}}},
  {18, {{-20,-5,HAZ_L}, {-4,-3,STONE}, {-2,2,HAZ_L}, {3,4,STONE}, {5,17,HAZ_L}, {18,20,HAZ_R}}},
  {19, {{-20,-5,HAZ_L}, {-4,-3,STONE}, {-2,2,HAZ_L}, {3,4,STONE}, {5,17,HAZ_L}, {18,20,HAZ_R}}},
  {20, {{-20,-5,HAZ_L}, {-4,-3,STONE}, {-2,2,HAZ_L}, {3,4,STONE}, {5,17,HAZ_L}, {18,20,HAZ_R}}},
}

return {
  reach = 20,
  rows  = rows,
}
