-- lib/names: all prototype names in one table. Centralized for renaming/verification.

local PREFIX = "oppenheimer-"

local function n(suffix) return PREFIX .. suffix end

local N = {}

N.prefix = PREFIX

-- --- core player-facing prototypes -------------------------------------------
N.turret          = n("artillery-turret")       -- entity + item + recipe (shared name)
N.shell           = n("artillery-shell")        -- ammo item + ammo-category (shared name)
-- N.cannon (the gun item) is GONE, deleted with prototypes/item.lua's gun
-- block -- the electric-turret chassis has no `gun =` field to hand it to.
N.projectile      = n("artillery-projectile")   -- artillery-projectile
N.remote          = n("artillery-remote")       -- capsule
N.flare           = n("artillery-flare")        -- artillery-flare entity

N.designator_shortcut = n("give-designator")
N.designator_input    = n("give-designator-input")
N.drag_input      = n("drag-start-input")
N.drag_input_alt  = n("drag-start-alt-input")

N.inert_category  = n("inert")

N.pylon           = n("capacitor-pylon")
N.pylon_group     = n("pylon")

N.substation      = n("lance-substation")
N.substation_group = n("substation")

N.ground_lamp     = n("installation-lamp")

N.ex_shockwave    = n("explosion-shockwave")
N.ex_firewave     = n("explosion-firewave")
N.ex_groundfire   = n("explosion-groundfire")
N.ex_release      = n("explosion-release")
N.ex_fireball     = n("explosion-fireball")
N.ex_cluster      = n("explosion-cluster")
N.ex_flash        = n("explosion-flash")
N.ex_cap          = n("explosion-mushroom-cap")
N.ex_carrier      = n("explosion-carrier")
N.ex_boom         = n("explosion-boom")

N.ex_wave         = n("explosion-wave")
N.ex_gather       = n("explosion-gather")
N.ex_gather_core  = n("explosion-gather-core")
N.fallout         = n("fallout")
N.fallout_cloud   = n("fallout-cloud")

-- The mod's own flame. MUST NOT spread: base's `fire-flame` carries
-- maximum_spread_count = 100, so every seed would become up to a hundred more.
N.scorch_flame    = n("scorch-flame")

-- THE SAME FLAME, ON A TREE -- needs its own prototype because Factorio does
-- not draw a fire's own `pictures` on a tree. Base's `fire-flame` points a
-- burning tree at a SECOND prototype (`spawn_entity = "fire-flame-on-tree"`,
-- its own pictures/alpha/tree_dying_factor); without the same redirect here a
-- burning tree shows a generic ground flame standing on green canopy. Cloned
-- from base's at load (its art is procedurally generated by fire-util) rather
-- than rebuilt by hand, with the same spread kill as N.scorch_flame.
N.scorch_flame_tree = n("scorch-flame-on-tree")
N.ex_flash_sustain = n("ex-flash-sustain")      -- #98b, the long white light

N.smoke_stem      = n("smoke-stem")             -- #92
N.smoke_cap       = n("smoke-cap")              -- #93, affected_by_wind
N.smoke_smoulder  = n("smoke-smoulder")
N.smoke_vent      = n("smoke-vent") -- barrel venting
N.smoke_dust      = n("smoke-dust") -- ignition shock ring
N.smoke_source    = n("smoulder-source")        -- particle-source, long burn

-- The staged detonation itself (#90). blast.lua generates the
-- delayed-active-trigger prototypes under this namespace.
N.strike          = n("strike")

-- --- yield variants (#83 + #101) ----------------------------------------------
-- The detonation is built once per SELECTABLE YIELD, because a trigger tree is
-- data-stage and cannot be scaled at runtime. Every generated name is derived
-- from the fraction so nothing has to keep a parallel list in step.
--
--   0.25 -> "25", and the carrier is <prefix>detonation-25
--
-- The carrier is an invisible explosion whose `created_effect` IS that step's
-- staged detonation; scripts/impact.lua creates the right one where the shell
-- lands. `created_effect` is declared on EntityPrototype, so it is available on
function N.ex_flash_for(fraction)
  return N.ex_flash .. "-" .. N.yield_tag(fraction)
end

function N.ex_wave_for(fraction, hstep)
  return N.ex_wave .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_firewave_for(fraction, hstep)
  return N.ex_firewave .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_groundfire_for(fraction, hstep)
  return N.ex_groundfire .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_release_for(fraction, hstep)
  return N.ex_release .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_flash_sustain_for(fraction)
  return N.ex_flash_sustain .. "-" .. N.yield_tag(fraction)
end

function N.ex_gather_for(fraction, hstep)
  return N.ex_gather .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_gather_core_for(fraction, hstep)
  return N.ex_gather_core .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
end

function N.ex_scorch_for(fraction)
  return n("scorchmark-") .. N.yield_tag(fraction)
end

function N.yield_tag(fraction)
  return tostring(math.floor(fraction * 100 + 0.5))
end

function N.detonation(fraction)
  return n("detonation-") .. N.yield_tag(fraction)
end

function N.wave_at(tag, kind)
  return n("wave-") .. kind .. "-" .. tag
end

--- Sphere lightning, per strike level. `kind` is bolt, hop, fork, impact, streamer or sky.
function N.lightning(kind, level)
  return n("lightning-") .. kind .. "-" .. tostring(level)
end

--- Lance: core and halo, per yield and per heat step.
function N.lance(layer, fraction, hstep, kind)
  return n("lance-") .. layer .. "-" .. N.yield_tag(fraction) .. "-h" .. tostring(hstep or 1)
         .. (kind == "mid" and "-m" or "")
end

N.gui = {
  yield_frame  = n("yield-frame"),
  yield_choice = n("yield-choice-"),
  fire_frame   = n("fire-frame"),
  fire_release = n("fire-release"),
  fire_abort   = n("fire-abort"),
  fire_status  = n("fire-status"),
  fire_ammo    = n("fire-ammo"),
  fire_bar     = n("fire-bar"),
  hud_frame    = n("hud"),
  hud_list     = n("hud-list"),
  hud_toggle   = n("hud-toggle"),
  -- The battery line above the controls: how many installations are linked and
  -- the multiplier they add up to.
  hud_bar      = n("hud-bar"),
  arc_sweep_toggle = n("arc-sweep-toggle"),
  fire_mode    = n("fire-mode"),
}

N.sound = {
  -- THE SPIN-UP, one entry per piece of sound/BeamCharge<NN>.ogg. The gun plays
  -- the LAST k of them so the whine always ends on the bang, and k follows how
  -- long the banks still have to fill. Length MUST equal C.sound.charge_parts.
  charge = {
    n("charge-01"), n("charge-02"), n("charge-03"), n("charge-04"),
    n("charge-05"), n("charge-06"), n("charge-07"), n("charge-08"),
    n("charge-09"), n("charge-10"), n("charge-11"), n("charge-12"),
  },
  strike = n("strike"),
  -- The lance winding down at the cut. Not `discharge`: that word already means
  -- ignition everywhere else in this mod (turret.discharge, C.sound.discharge_at).
  spindown = n("spindown"),
  fire   = n("fire"),
  boom   = n("boom"),
  sear   = n("sear"),
  -- The lightning's thunder, keyed by strike level (sound/ThunderLevel<NN>.ogg).
  thunder = {
    [2] = n("thunder-02"), [3] = n("thunder-03"), [4] = n("thunder-04"),
    [5] = n("thunder-05"), [6] = n("thunder-06"), [7] = n("thunder-07"),
    [8] = n("thunder-08"), [9] = n("thunder-09"), [10] = n("thunder-10"),
  },
  arc_sweep = n("arc-sweep"),
  arc_sweep_charge = n("arc-sweep-charge"),
  ui_click  = n("ui-click"),
  ui_select = n("ui-select"),
  ui_arm    = n("ui-arm"),
  ui_notice = n("ui-notice"),
  ui_ok     = n("ui-ok"),
  ui_alert  = n("ui-alert"),
}

N.fx = {
  detonated   = n("fx-detonated"),
  fired       = n("fx-fired"),
}

N.anim = {
  bank_charge = n("bank-charge"),
  turret_head = n("turret-head"),
  turret_head_glow   = n("turret-head-glow"),
  turret_head_shadow = n("turret-head-shadow"),
}

N.sprite = {
  stage_scorch = {n("stage-scorch-1"), n("stage-scorch-2")},
  ion_glow     = n("ion-glow"),
}

N.tech = {
  artillery       = n("artillery"),
  capacity        = n("installation-capacity-1"),
  capacity_locale = n("installation-capacity"),
}

N.command = {
  status = "oppenheimer-status",
  count  = "oppenheimer-count",
  fire   = "oppenheimer-fire",
  hud    = "oppenheimer-hud",
  muzzle = "oppenheimer-muzzle",
  profile = "oppenheimer-profile",
}

N.setting = {
  prep_rate = n("prepare-chunk-rate"),
}

N.style = {
  button       = "oppenheimer_button",
  button_green = "oppenheimer_button_green",
  button_red   = "oppenheimer_button_red",
  button_fire  = "oppenheimer_button_fire",
  -- TEST/LIVE, one style per lit side (prototypes/style.lua).
  switch_test  = "oppenheimer_switch_test",
  switch_live  = "oppenheimer_switch_live",
  dropdown     = "oppenheimer_dropdown",
  graph_bar    = "oppenheimer_graph_bar",
}

N.sprite_gui = {
  graph_hot  = n("graph-hot"),
  graph_warm = n("graph-warm"),
  graph_cold = n("graph-cold"),
  graph_dim  = n("graph-dim"),
}

N.base = {
  muzzle_flash        = "artillery-cannon-muzzle-flash",
  laser_turret_remnants  = "laser-turret-remnants",
  laser_turret_explosion = "laser-turret-explosion",
  scorchmark_medium   = "medium-scorchmark-tintable",
  scorchmark_huge     = "huge-scorchmark",
  nuclear_ground      = "nuclear-ground",
  fire_flame          = "fire-flame",
  volcanic_folds      = "volcanic-folds",
  volcanic_folds_warm   = "volcanic-folds-warm",
  volcanic_smooth_stone = "volcanic-smooth-stone",
  volcanic_jagged_ground = "volcanic-jagged-ground",
  volcanic_cracks       = "volcanic-cracks",
  volcanic_cracks_warm  = "volcanic-cracks-warm",
  volcanic_cracks_hot   = "volcanic-cracks-hot",
  lava                = "lava",
  lava_hot            = "lava-hot",
  water_shallow       = "water-shallow",
  water_mud           = "water-mud",
  nuclear_smoke       = "nuclear-smoke",
  atomic_shockwave    = "atomic-nuke-shockwave",
  atomic_fire_smoke   = "atomic-fire-smoke",
  cluster_nuke        = "cluster-nuke-explosion",
  nuke_explosion      = "nuke-explosion",
}

return N
