-- scripts/pylon.lua -----------------------------------------------------------------
-- Pylon linkage and energy draw.
--
-- THE CORE IDEA: the gun does not consume power (ArtilleryTurretPrototype has
-- no energy_source), so buffered companion entities stand around it and the
-- rest of the mod decides whether the gun may fire based on what they hold --
-- which gives "powered from four sides" and "charge-up time" (fire rate is
-- how fast the grid refills the banks) from one mechanism.
--
-- Not tracked in `storage`: LuaEntity.energy is read/write on the banks
-- directly, so the buffer IS the state, already saved and synced, with no
-- second source of truth that could disagree after a migration or a
-- blueprint paste. These are electric-energy-interface entities, not
-- accumulators -- see prototypes/entity/pylon.lua for why -- but `energy`
-- reads/writes identically on both, so nothing in this file cares.
--------------------------------------------------------------------------------------

local C      = require("config")
local N      = require("lib.names")
local events = require("scripts.events")
local schema = require("scripts.schema")

local pylon = {}

-- Every prototype name that counts as a pylon.
local PYLON_NAMES = {[N.pylon] = true}
pylon.NAMES = PYLON_NAMES

-- The masts. Tracked here rather than in a module of their own because this file
-- is already "the installation's hardware, and which turret owns it" -- a second
-- module would duplicate the link/unlink/adopt machinery verbatim for one extra
-- entity.
--
-- A mast has NO SLOT. A bank does, because which slot it occupies decides the
-- asymmetric drain (#65) and has to survive a save. A mast only has to be known,
-- so rec.masts is a plain set: nothing about the installation depends on which
-- corner a given mast is standing in.
local MAST_NAMES = {[N.substation] = true}
pylon.MAST_NAMES = MAST_NAMES

-- SCRATCH: [turret unit_number] = joules read this tick (pylon.available). Every
-- bank write or link change in this file clears the installation's entry.
local AVAIL_TICK, AVAIL = -1, {}

local function forget(turret_un)
  if turret_un then AVAIL[turret_un] = nil end
end

-- =============================================================================
-- Geometry
-- =============================================================================

--- Where the SIXTEEN banks belong, relative to a turret's centre.
--
-- Four straight rows of four, one parallel to each edge of the gun, generated by
-- C.pylon_slot_defs. Keys are "north-1" .. "west-4"; a record's rec.pylons is
-- keyed the same way, so which physical slot a bank occupies survives a save.
--
-- Only four are REQUIRED (C.pylon.count). The rest are how far the yield
-- selector can reach -- see the note on count in config.lua.
function pylon.slots(center)
  local out = {}
  for _, def in ipairs(C.pylon_slot_defs()) do
    out[def.key] = {x = center.x + def.ox, y = center.y + def.oy}
  end
  return out
end

--- Which slot, if any, a position corresponds to for a given turret.
-- Tolerance is generous: the player places the pylon roughly, and a pylon that
-- is one tile off should still link rather than silently do nothing.
--
-- NEAREST **FREE** SLOT: `occupied` is handed to the search rather than
-- checked after it, because with sixteen banks in 2x2 clusters (4 tiles apart
-- against a 2.5 tile tolerance), two banks placed a little off centre
-- routinely resolve to the same nearest slot -- refusing outright rather than
-- trying the next slot out silently drops one of them to an ordinary,
-- unlinked buffered entity.
--
-- @param occupied table|nil  set of slot keys already taken, skipped if given
function pylon.slot_for(turret_pos, pos, occupied)
  local best, best_d = nil, C.pylon.link_tolerance
  for key, slot in pairs(pylon.slots(turret_pos)) do
    if not (occupied and occupied[key]) then
      local dx, dy = slot.x - pos.x, slot.y - pos.y
      local d = math.sqrt(dx * dx + dy * dy)
      if d <= best_d then best, best_d = key, d end
    end
  end
  return best
end

-- =============================================================================
-- Linkage
-- =============================================================================

--- Attach a pylon entity to whichever turret it is standing next to.
function pylon.link(entity)
  if not (entity and entity.valid and entity.unit_number) then return end

  -- RADIAL, not the axis-aligned pad half-width: find_entities_filtered's
  -- `radius` describes a CIRCLE, and the outermost bank of each cluster
  -- stands far enough out on the diagonal that an axis-extent-sized radius
  -- misses it -- silently leaving it an ordinary, unlinked buffered entity
  -- (the tell: full at rest, since every linked bank is held at zero).
  local reach = C.pylon_link_radius()
  local candidates = entity.surface.find_entities_filtered{
    name = N.turret,
    position = entity.position,
    radius = reach,
    force = entity.force,
  }

  for _, turret in pairs(candidates) do
    local rec = storage.turrets[turret.unit_number]
    if rec then
      -- Nearest FREE slot: the occupancy is handed to the search rather than
      -- checked after it, so a bank whose closest slot is taken lands in the
      -- next one out instead of being thrown away. See pylon.slot_for.
      local side = pylon.slot_for(turret.position, entity.position, rec.pylons)
      if side then
        rec.pylons[side] = entity.unit_number
        storage.pylons[entity.unit_number] = {
          turret = turret.unit_number, side = side, entity = entity,
        }
        forget(turret.unit_number)
        return turret.unit_number, side
      end
    end
  end
end

--- Attach a mast to whichever installation it is standing at the corner of.
--
-- NEAREST turret, not first found, because two installations placed at the
-- exclusion radius can both have a given mast inside their search circle and
-- "whichever the entity search happened to return first" is not a rule anyone
-- can predict from looking at the map.
function pylon.link_mast(entity)
  if not (entity and entity.valid and entity.unit_number) then return end
  if storage.masts[entity.unit_number] then return end

  local best, best_d2
  local candidates = entity.surface.find_entities_filtered{
    name = N.turret,
    position = entity.position,
    radius = C.substation_link_radius(),
    force = entity.force,
  }
  for _, t in pairs(candidates) do
    local rec = storage.turrets[t.unit_number]
    if rec then
      local dx = t.position.x - entity.position.x
      local dy = t.position.y - entity.position.y
      local d2 = dx * dx + dy * dy
      if not best_d2 or d2 < best_d2 then best, best_d2 = rec, d2 end
    end
  end
  if not best then return end

  best.masts = best.masts or {}
  best.masts[entity.unit_number] = entity
  storage.masts[entity.unit_number] = best.unit_number
  return best.unit_number
end

--- A mast died or was mined.
function pylon.unlink_mast(unit_number)
  local owner = storage.masts[unit_number]
  if not owner then return end
  local rec = storage.turrets[owner]
  if rec and rec.masts then rec.masts[unit_number] = nil end
  storage.masts[unit_number] = nil
end

--- Every live mast of an installation, dropping any that died unobserved.
function pylon.masts(rec)
  local out = {}
  for un, e in pairs(rec.masts or {}) do
    if e and e.valid then
      out[#out + 1] = e
    else
      pylon.unlink_mast(un)
    end
  end
  return out
end

--- A turret was just built: adopt any pylons already standing in its slots.
function pylon.adopt_existing(rec)
  if not schema.valid(rec) then return end
  local e = rec.entity
  -- Same radial reach as pylon.link, and for the same reason. These two searches
  -- must agree or a bank links when it is built and is dropped when the turret
  -- is rebuilt, which is worse than either failing on its own.
  local found = e.surface.find_entities_filtered{
    position = e.position,
    radius = math.max(C.pylon_link_radius(), C.substation_link_radius()),
    force = e.force,
  }
  for _, p in pairs(found) do
    if PYLON_NAMES[p.name] and p.unit_number
       and not storage.pylons[p.unit_number] then
      local side = pylon.slot_for(e.position, p.position, rec.pylons)
      if side then
        rec.pylons[side] = p.unit_number
        storage.pylons[p.unit_number] = {
          turret = rec.unit_number, side = side, entity = p,
        }
        forget(rec.unit_number)
      end
    elseif MAST_NAMES[p.name] and p.unit_number
       and not storage.masts[p.unit_number] then
      -- The search radius above is the wider of the two, so a mast standing at
      -- the corner is inside it; the per-entity distance test is link_mast's.
      pylon.link_mast(p)
    end
  end
end

--- #66: a pylon died or was mined. The gun goes quiet until it is rebuilt.
function pylon.unlink(unit_number)
  local link = storage.pylons[unit_number]
  if not link then return end
  local rec = storage.turrets[link.turret]
  if rec and rec.pylons[link.side] == unit_number then
    rec.pylons[link.side] = nil
  end
  forget(link.turret)
  storage.pylons[unit_number] = nil
end

-- =============================================================================
-- Energy
-- =============================================================================

--- Total joules currently stored across a turret's pylons. `fresh` skips this
--- tick's memo, for a reader that must see what the grid delivered since.
function pylon.available(rec, fresh)
  local t = game.tick
  if AVAIL_TICK ~= t then
    AVAIL_TICK = t
    AVAIL = {}
  end
  local un0 = rec.unit_number
  if not fresh then
    local v = AVAIL[un0]
    if v then return v end
  end
  local total = 0
  for _, un in pairs(rec.pylons or {}) do
    local link = storage.pylons[un]
    local e = link and link.entity
    if e and e.valid then
      total = total + e.energy
    else
      -- The entity died without us seeing the event (another mod, /editor).
      pylon.unlink(un)
    end
  end
  AVAIL[un0] = total
  return total
end

-- =============================================================================
-- THE METER
--
-- What limits an electric consumer's intake in one tick is
--     min(input_flow_limit / 60,  buffer_capacity - energy)
-- and only ONE of those two is writable at runtime. `input_flow_limit` is a
-- getter with no setter -- get_electric_input_flow_limit(), confirmed in the
-- shipped 2.0.77 spec. `electric_buffer_size` is an attribute, and the spec says
-- outright that "write access is limited to the ElectricEnergyInterface type".
--
-- So the buffer is the dial, and writing it every tick is how a player-typed
-- wattage becomes a real, metered, graph-visible draw.
-- =============================================================================

--- The prototype buffer of a bank -- the CEILING on a runtime write.
--
-- A write to electric_buffer_size is not checked against the prototype, so
-- without clamping here, a four-bank installation told to charge at 15 GJ/s
-- would simply be handed a 240 GJ buffer and would hold it -- and "how much
-- capacitor did you build" would stop meaning anything at all. Cached lazily
-- on first use because C.pylon_buffer() reads values config derives at load
-- time.
local MAX_BUFFER

local function max_buffer_of(entity)
  if not MAX_BUFFER then MAX_BUFFER = C.pylon_buffer() end
  if entity.name ~= N.pylon then return nil end
  return MAX_BUFFER
end

pylon.max_buffer_of = max_buffer_of

--- Set every linked bank's buffer to `each` joules, clamped to the prototype
--- ceiling.
--
-- @return number the total buffer actually granted across the installation
function pylon.set_buffer(rec, each)
  local total = 0
  for _, un in pairs(rec.pylons or {}) do
    local link = storage.pylons[un]
    local e = link and link.entity
    if e and e.valid then
      local cap = max_buffer_of(e)
      if cap then
        local want = each
        if want > cap then want = cap end
        if want < 0 then want = 0 end
        -- Written only when it actually differs. At rest this is the same value
        -- forever, and this runs every tick for every bank of every
        -- installation; during the ramp it changes every tick and the compare
        -- costs nothing next to the write it is guarding.
        if e.electric_buffer_size ~= want then
          e.electric_buffer_size = want
          forget(rec.unit_number)
        end
        total = total + want
      end
    end
  end
  return total
end

-- NEVER WRITE LuaEntity.power_usage ON A BANK. It is not a display field: it
-- is an engine-side BURN out of the bank's own buffer every tick (J/tick),
-- invisible to the meter above. 0.35.0 wrote it to "fix" the tooltip's 0 W
-- Consumption line and it ate the charge as fast as the grid delivered it --
-- every bank pinned at its input_flow_limit, the banks never filling past one
-- tick's delivery, shots firing at ~1%. The 0 W readout is the accepted cost of
-- the buffer-as-meter model; see prototypes/entity/pylon.lua's energy_usage.

--- Pin every bank's buffer to exactly what it is currently holding, called
--- right after turret.power_tick drains the discharge. WITHOUT THIS, draining
--- a bank just opens room under whatever ceiling the ramp left in
--- electric_buffer_size, and the grid refills that room for the whole
--- discharge -- doubling the real cost of every shot. PER BANK, NOT AN
--- INSTALLATION MEAN: #65's asymmetric drain leaves banks holding visibly
--- different amounts, and a mean ceiling written below what a fuller bank
--- holds would discard its surplus outright.
function pylon.freeze(rec)
  for _, un in pairs(rec.pylons or {}) do
    local link = storage.pylons[un]
    local e = link and link.entity
    if e and e.valid and max_buffer_of(e) then
      local held = e.energy
      if e.electric_buffer_size ~= held then
        e.electric_buffer_size = held
        forget(rec.unit_number)
      end
    end
  end
end

--- Total buffer across a turret's pylons -- the denominator for "how charged".
function pylon.capacity(rec)
  local total = 0
  for _, un in pairs(rec.pylons or {}) do
    local link = storage.pylons[un]
    local e = link and link.entity
    if e and e.valid then
      total = total + e.electric_buffer_size
    end
  end
  return total
end

--- Draw `joules` out of a turret's pylons.
-- #65: ASYMMETRIC DRAIN. The pylon nearest the firing bearing gives up the most,
-- so a gun that always fires east develops a visibly uneven bank. Costs nothing,
-- and it is the kind of detail that makes a machine feel like it is actually
-- doing work rather than running a timer.
function pylon.drain(rec, joules, bearing)
  forget(rec.unit_number)
  local weights, total_w = {}, 0
  for side, un in pairs(rec.pylons or {}) do
    local v = C.pylon_slot_dir(side)
    local w = 1.0
    if bearing and v then
      -- dot product of the pylon direction with the firing direction: 1 when
      -- the pylon is directly toward the target, -1 when directly behind.
      local dot = v[1] * bearing.x + v[2] * bearing.y
      w = 1.0 + C.pylon.drain_bias * dot
      if w < 0.1 then w = 0.1 end
    end
    weights[side] = w
    total_w = total_w + w
  end
  if total_w <= 0 then return 0 end

  local drawn = 0
  for side, un in pairs(rec.pylons or {}) do
    local link = storage.pylons[un]
    local e = link and link.entity
    if e and e.valid then
      local want = joules * (weights[side] / total_w)
      local take = math.min(want, e.energy)
      e.energy = e.energy - take
      drawn = drawn + take
    end
  end

  -- A favoured bank runs dry before the discharge ends; its unmet share goes to
  -- the banks still holding, pro rata to what they hold. Without this the rear
  -- banks finished every shot still charged while the front ones sat empty.
  local short = joules - drawn
  if short > 1 then
    local left = 0
    for _, un in pairs(rec.pylons or {}) do
      local link = storage.pylons[un]
      local e = link and link.entity
      if e and e.valid then left = left + e.energy end
    end
    if left > 0 then
      local frac = math.min(1, short / left)
      for _, un in pairs(rec.pylons or {}) do
        local link = storage.pylons[un]
        local e = link and link.entity
        if e and e.valid and e.energy > 0 then
          local take = e.energy * frac
          e.energy = e.energy - take
          drawn = drawn + take
        end
      end
    end
  end
  return drawn
end

--- Unit vector from a turret toward what it is shooting at, for #65.
function pylon.bearing(rec)
  local e = rec.entity
  if not (e and e.valid) then return nil end
    -- NOT `shooting_target`: reading it throws on this entity class. The aim
    -- point is the one scripts/targeting.lua records.
  local aim = rec.aim
  if not aim then return nil end
  local dx = aim.x - e.position.x
  local dy = aim.y - e.position.y
  local len = math.sqrt(dx * dx + dy * dy)
  if len < 0.001 then return nil end
  return {x = dx / len, y = dy / len}
end

-- =============================================================================
-- Events
-- =============================================================================

-- ONE handler for both families, dispatched on the name.
--
-- Not two registrations: the dispatcher unions the filters of every registrant
-- for an event, so a second registration would only widen the same filter list
-- and then hand every bank to a mast handler that has to re-check the name
-- anyway. Checking it once here is the same work with one place to look.
function pylon.on_built(event)
  local entity = event.entity
  if not (entity and entity.valid) then return end
  if MAST_NAMES[entity.name] then
    pylon.link_mast(entity)
  else
    pylon.link(entity)
  end
end

function pylon.on_removed(event)
  local entity = event.entity
  if not (entity and entity.valid and entity.unit_number) then return end
  if MAST_NAMES[entity.name] then
    pylon.unlink_mast(entity.unit_number)
  else
    pylon.unlink(entity.unit_number)
  end
end

local filter = {}
for name in pairs(PYLON_NAMES) do
  filter[#filter + 1] = {filter = "name", name = name}
end
for name in pairs(MAST_NAMES) do
  filter[#filter + 1] = {filter = "name", name = name}
end

events.on(defines.events.on_built_entity,       pylon.on_built, filter)
events.on(defines.events.on_robot_built_entity, pylon.on_built, filter)
events.on(defines.events.script_raised_built,   pylon.on_built, filter)
events.on(defines.events.script_raised_revive,  pylon.on_built, filter)

events.on(defines.events.on_player_mined_entity, pylon.on_removed, filter)
events.on(defines.events.on_robot_mined_entity,  pylon.on_removed, filter)
events.on(defines.events.on_entity_died,         pylon.on_removed, filter)
events.on(defines.events.script_raised_destroy,  pylon.on_removed, filter)

return pylon
